/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_ECMTune */

#ifndef _Included_org_gmplib_gmpjni_ECMTune
#define _Included_org_gmplib_gmpjni_ECMTune
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gmplib_gmpjni_ECMTune
 * Method:    bench_mulredc
 * Signature: (IIILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECMTune_bench_1mulredc
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring);

/*
 * Class:     org_gmplib_gmpjni_ECMTune
 * Method:    native_tune
 * Signature: (IIIJLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_ECMTune_native_1tune
  (JNIEnv *, jclass, jint, jint, jint, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
